spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leadnews_article
    username: root
    password: SXY-E.YT
    driver-class-name: com.mysql.cj.jdbc.Driver
    application:
      name: leadnews-article

springdoc:
  swagger-ui:
    tags-sorter: alpha
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: FJH_03
    password: SXY-E.YT

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: cnsr.fjh03.model.article.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
